## numpy
* 是一组数的容器，并能进行科学运算
* python有list为什么还需要numpy?因为list在处理少量同类型数据性能还可以，但处理大量同类型数据时，速度慢、内存占用多、
## ndArray（n维数组） 
* 1.必须是‘矩形’，不能是‘阶梯形’
* 2.shape可以变，但size不能变
* 3.数据类型一样

In [2]:
import numpy as np

1.有几个中括号，就是几维

In [54]:
n_shape1 = np.array([1,2,3,4])
print(n_shape1.ndim)

1


In [55]:
n_shape2 = np.array([[1,2,3,4]])
print(n_shape2.ndim)

2


2.索引和切片

In [56]:
print(n_shape1[0],n_shape1[-1])

1 4


In [57]:
n_shape1[0] = 10
n_shape1

array([10,  2,  3,  4])

In [12]:
n_shape1[:-1]

array([10,  2,  3])

In [13]:
n_shape1[:]

array([10,  2,  3,  4])

In [14]:
n_shape1[::2]

array([10,  3])

In [58]:
n_shape22 = np.array([[1,2,3,4],[1,1,2,4],[3,2,3,4],[6,22,3,4]])
n_shape22

array([[ 1,  2,  3,  4],
       [ 1,  1,  2,  4],
       [ 3,  2,  3,  4],
       [ 6, 22,  3,  4]])

In [59]:
n_shape22[0,1]

2

In [60]:
n_shape22[0,:]

array([1, 2, 3, 4])

In [61]:
n_shape22[:,1]

array([ 2,  1,  2, 22])

In [62]:
n_shape22[:2,:]

array([[1, 2, 3, 4],
       [1, 1, 2, 4]])

3.属性

In [63]:
n_shape1.shape

(4,)

In [64]:
n_shape2.shape

(1, 4)

In [28]:
n_shape1.size

16

In [29]:
#整数默认int32 浮点数默认float64
n_shape1.dtype

dtype('int32')

4.方法

In [30]:
np.zeros(4)

array([0., 0., 0., 0.])

In [31]:
np.ones(2)

array([1., 1.])

In [36]:
np.empty(2)

array([1., 1.])

In [37]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [34]:
np.arange(2,6,2)

array([2, 4])

In [38]:
#在[0,1] 之间取6个数，包含0 、1 ，且间距相同
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [40]:
np.ones(3,dtype=np.int32)

array([1, 1, 1])

In [65]:
#原数组顺序不变
np.sort(n_shape1)

array([ 2,  3,  4, 10])

In [52]:
n1 = np.array([[1,2,3,4],[3,4,2,1]])
n2 = np.array([[8,8,7,6]])
n3 = np.array([[6,6],[6,5]])
np.concatenate((n1,n2),axis=0)
np.concatenate((n1,n3),axis=1)

array([[1, 2, 3, 4, 6, 6],
       [3, 4, 2, 1, 6, 5]])

In [71]:
#n1 = n_shape1.reshape(1,4)
n2 = np.reshape(n1,newshape=(2,2))
n2

array([[10,  2],
       [ 3,  4]])

高维数组

In [53]:
n_shape3 = np.array([[[2,3,4,5],[2,3,4,5]],
                     [[2,3,4,5],[2,3,4,5]],
                     [[2,3,4,5],[2,3,4,5]],
                     [[2,3,4,5],[2,3,4,5]]])
n_shape3.shape

(4, 2, 4)

扩展维度

In [83]:
#n1 = np.array([40,50,60,33])
n1 = np.array([[40,50,60,33],[44,66,77,22]])
n1.shape

(2, 4)

In [81]:
#在行方向增加一个维度
#n2 = n1[np.newaxis,:] #行向量
#n2 = n1.reshape(1,n1.size)
n2 = np.expand_dims(n1,axis=0)
n2

array([[[40, 50, 60, 33],
        [44, 66, 77, 22]]])

In [82]:
#n3 = n1[:,np.newaxis] #列向量
#n3 = n1.reshape(n1.size,1)
n3 = np.expand_dims(n1,axis=1)
n3

array([[[40, 50, 60, 33]],

       [[44, 66, 77, 22]]])

按条件取值

In [88]:
n1 = np.array([[40,50,60,33],[44,66,77,22]])
n1>40

array([[False,  True,  True, False],
       [ True,  True,  True, False]])

In [86]:
n1[n1>40]

array([50, 60, 44, 66, 77])

In [87]:
n1[(n1>40) | (n1==40)]

array([40, 50, 60, 44, 66, 77])

In [95]:
#找到满足条件的元素位置
b = np.nonzero(n1>40)
#print(type(b))
print(b)
#根据位置查找元素
n1[b]

<class 'tuple'>
(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))


array([50, 60, 44, 66, 77])

按不同方向拼接数组

In [97]:
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [98]:
a2 = np.array([[2,5],[8,4]])
a2

array([[2, 5],
       [8, 4]])

In [99]:
a3 = np.vstack((a1,a2))
a3

array([[1, 2],
       [3, 4],
       [2, 5],
       [8, 4]])

In [100]:
a4 = np.hstack((a1,a2))
a4

array([[1, 2, 2, 5],
       [3, 4, 8, 4]])

按不同方向切割数组

In [3]:
a1 = np.arange(1,25).reshape(2,12)
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [6]:
#水平方向 平均分4份
np.hsplit(a1,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [7]:
#水平方向 按指定位置拆分
np.hsplit(a1,(4,7))

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11, 12],
        [20, 21, 22, 23, 24]])]

引用和拷贝

In [101]:
n1 = np.array([[0,8,8,6],[3,5,57,7]])
n1

array([[ 0,  8,  8,  6],
       [ 3,  5, 57,  7]])

In [104]:
n1[0,0] = 100
n1

array([[100,   8,   8,   6],
       [  3,   5,  57,   7]])

In [105]:
n2 = n1.copy()
n2[0][0] = 0
n2

array([[ 0,  8,  8,  6],
       [ 3,  5, 57,  7]])

In [106]:
n1

array([[100,   8,   8,   6],
       [  3,   5,  57,   7]])

基本运算
* 加、减、乘、除、取余、整除 ，都是对应位置上进行。shape不同，会自动进行填充为相同shape后再进行相关运算

In [110]:
n1 = np.array([[9,88,22,3],[2,3,6,7]])
n2 = np.array([2,3,4,5])

In [111]:
n1+n2

array([[11, 91, 26,  8],
       [ 4,  6, 10, 12]])

In [112]:
n1-n2

array([[ 7, 85, 18, -2],
       [ 0,  0,  2,  2]])

In [114]:
n1*n2

array([[ 18, 264,  88,  15],
       [  4,   9,  24,  35]])

In [115]:
n1/n2

array([[ 4.5       , 29.33333333,  5.5       ,  0.6       ],
       [ 1.        ,  1.        ,  1.5       ,  1.4       ]])

In [116]:
n1%n2

array([[1, 1, 2, 3],
       [0, 0, 2, 2]])

In [117]:
n1//n2

array([[ 4, 29,  5,  0],
       [ 1,  1,  1,  1]])

In [118]:
n1*2

array([[ 18, 176,  44,   6],
       [  4,   6,  12,  14]])

In [120]:
n1.sum()

140

In [121]:
n1.min()

2

In [123]:
n1.max()

88

In [125]:
n1.min(axis=0)

array([2, 3, 6, 3])

In [126]:
n1.min(axis=1)

array([3, 2])

In [127]:
n1.max(axis=0)

array([ 9, 88, 22,  7])

In [128]:
n1.max(axis=1)

array([88,  7])

In [129]:
n1[1:2]

array([[2, 3, 6, 7]])

In [131]:
np.ones((3,))

array([1., 1., 1.])

In [132]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [133]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [143]:
rng = np.random.default_rng()
rng.random(5,)

array([0.73053991, 0.43393366, 0.77289985, 0.28654211, 0.8069217 ])

In [144]:
rng.random((4,3,2))

array([[[0.11332506, 0.30007447],
        [0.64448339, 0.06153767],
        [0.01318903, 0.23335395]],

       [[0.79055547, 0.66238689],
        [0.66185045, 0.45589877],
        [0.79686468, 0.77758391]],

       [[0.19968316, 0.76501597],
        [0.45471317, 0.93029647],
        [0.4325205 , 0.98295647]],

       [[0.81593599, 0.88402367],
        [0.12577856, 0.8015491 ],
        [0.91037982, 0.02872202]]])

In [145]:
rng.integers(2,10,(3,4))

array([[4, 5, 7, 9],
       [9, 2, 7, 3],
       [9, 2, 4, 6]], dtype=int64)

去重

In [8]:
a1 = np.array([11,11,12,13,14,15,16,17,12,13,11,14,18, 19,20])
a1

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [9]:
unique_a1 = np.unique(a1)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
np.unique(a1, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [14]:
np.unique(a1, return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [37]:
a2 = np.array([[1,2,3,4],[1,4,2,1],[1,6,7,5],[1,33,33,66]])
print(a2)

[[ 1  2  3  4]
 [ 1  4  2  1]
 [ 1  6  7  5]
 [ 1 33 33 66]]


In [38]:
np.unique(a2)

array([ 1,  2,  3,  4,  5,  6,  7, 33, 66])

In [41]:
#唯一行
a3 = np.unique(a2, axis=0)
print(a3)

[[ 1  2  3  4]
 [ 1  4  2  1]
 [ 1  6  7  5]
 [ 1 33 33 66]]


In [40]:
#唯一列
a4 = np.unique(a2, axis=1)
print(a4)

[[ 1  2  3  4]
 [ 1  4  2  1]
 [ 1  6  7  5]
 [ 1 33 33 66]]


In [49]:
a3 = np.array([[1, 2, 3, 1], [5, 6, 7, 5], [9, 10, 11, 9], [1, 2, 3, 1]])
print('a3:', a3, sep='\n')
# 沿指定的轴方向去除数值完全相同的
u_a31 = np.unique(a3, axis=0)
print('a3中axis=0：', u_a31, sep='\n')  # 去除值完全相同行
u_a32 = np.unique(a3, axis=1)
print('a3中axis=1：', u_a32, sep='\n')  # 去除值完全相同列


a3:
[[ 1  2  3  1]
 [ 5  6  7  5]
 [ 9 10 11  9]
 [ 1  2  3  1]]
a3中axis=0：
[[ 1  2  3  1]
 [ 5  6  7  5]
 [ 9 10 11  9]]
a3中axis=1：
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [ 1  2  3]]


转置

In [51]:
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)

[[1 2 3]
 [4 5 6]]


In [52]:
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
a1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
a1.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

反转

In [55]:
a1 = np.arange(7)
a1

array([0, 1, 2, 3, 4, 5, 6])

In [56]:
np.flip(a1)

array([6, 5, 4, 3, 2, 1, 0])

In [58]:
a2 = np.arange(6).reshape(3,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
#行和列均反转
np.flip(a2)

array([[5, 4],
       [3, 2],
       [1, 0]])

In [62]:
#所有行反转
np.flip(a2, axis=0)

array([[4, 5],
       [2, 3],
       [0, 1]])

In [61]:
#所有列反转
np.flip(a2, axis=1)

array([[1, 0],
       [3, 2],
       [5, 4]])

In [63]:
#指定行反转
a2[1] = np.flip(a2[1])
a2

array([[0, 1],
       [3, 2],
       [4, 5]])

In [64]:
#指定列反转
a2[:,1] = np.flip(a2[:,1])
a2

array([[0, 5],
       [3, 2],
       [4, 1]])

数组的降维

In [65]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a2 = a1.flatten()
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
#flatten() 方法对原数组没影响
a2[0] = 99
print(a2)
print(a1)

[99  2  3  4  5  6  7  8  9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
a3 = a1.ravel()
a3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
#ravel() 方法对原数组有影响
a3[0] = 99
print(a3)
print(a1)

[99  2  3  4  5  6  7  8  9]
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


保存和加载

In [70]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.save('./numpyData',a1)

In [73]:
a2 = np.load('./numpyData.npy')
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
np.savetxt('./numpyData.csv',a1)

In [76]:
a3 = np.loadtxt('./numpyData.csv')
a3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])